gcp_credentials = "intense-agency-364605-4bbb674a925f.json"
gcp_project_id = "intense-agency-364605"
gcp_region = "us-central1"
gke_zones = [ "us-central1" ]
gke_regional = false
gke_network = "default"
gke_subnetwork = "default"
gke_service_account_name  = "terraform@intense-agency-364605.iam.gserviceaccount.com"
gke_cluster_name = "stefan-test-cluster-test" 
gke_default_nodepool_name = "stefan-pool-test"